complete -c mdview -s h -l help -d 'Show help'
complete -c mdview -l version -d 'Print version and exit'
complete -c mdview -l print-config -d 'Print a commented YAML template'
complete -c mdview -l init-config -d 'Write a config template if missing'
complete -c mdview -l theme -r -d 'Select the viewer theme' -a 'github dracula solarized tempus-rift midnight paper'
complete -c mdview -l syntax-theme -r -d 'Select the code theme' -a 'github dracula solarized tempus-rift midnight paper'
complete -c mdview -l refresh -r -d 'Set refresh interval'
complete -c mdview -l refresh-interval -r -d 'Set refresh interval'
complete -c mdview -l timeout -r -d 'Set network timeout'
complete -c mdview -l max-bytes -r -d 'Set maximum input size'
complete -c mdview -l padding -r -d 'Set horizontal padding'
complete -c mdview -l wrap -r -d 'Set wrapping state'
complete -c mdview -l no-wrap -d 'Disable wrapping'
complete -c mdview -l watch -d 'Enable file watching'
complete -c mdview -l no-watch -d 'Disable file watching'
complete -c mdview -l config -r -d 'Config file path' -a '(__fish_complete_path)'
